In [1]:
import pandas as pd
import numpy as np

In [2]:
auctions = pd.read_csv('../datos/auctions.csv', low_memory=False)

In [3]:
auctions['date'] = pd.to_datetime(auctions['date'])

In [4]:
w1 = auctions[auctions['date'].dt.day < 21]
w2 = auctions[(auctions['date'].dt.day > 18) & (auctions['date'].dt.day < 22)]
w3 = auctions[(auctions['date'].dt.day > 19) & (auctions['date'].dt.day < 23)]
w4 = auctions[(auctions['date'].dt.day > 20) & (auctions['date'].dt.day < 24)]
w5 = auctions[(auctions['date'].dt.day > 21) & (auctions['date'].dt.day < 25)]
w6 = auctions[(auctions['date'].dt.day > 22) & (auctions['date'].dt.day < 26)]
w7 = auctions[(auctions['date'].dt.day > 23) & (auctions['date'].dt.day < 27)]

In [5]:
windowStart = pd.to_datetime("2019-04-18 00:00:00.000000")
w1['timeFromWindowStart'] = (w1['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-19 00:00:00.000000")
w2['timeFromWindowStart'] = (w2['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-20 00:00:00.000000")
w3['timeFromWindowStart'] = (w3['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-21 00:00:00.000000")
w4['timeFromWindowStart'] = (w4['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-22 00:00:00.000000")
w5['timeFromWindowStart'] = (w5['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-23 00:00:00.000000")
w6['timeFromWindowStart'] = (w6['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-23 00:00:00.000000")
w7['timeFromWindowStart'] = (w7['date'] - windowStart)/np.timedelta64(1,'s')

/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = va

In [6]:
w1 = w1.sort_values(by=['device_id', 'date'])
w1 = w1.drop_duplicates('device_id', keep = 'first')
w2 = w2.sort_values(by=['device_id', 'date'])
w2 = w2.drop_duplicates('device_id', keep = 'first')
w3 = w3.sort_values(by=['device_id', 'date'])
w3 = w3.drop_duplicates('device_id', keep = 'first')
w4 = w4.sort_values(by=['device_id', 'date'])
w4 = w4.drop_duplicates('device_id', keep = 'first')
w5 = w5.sort_values(by=['device_id', 'date'])
w5 = w5.drop_duplicates('device_id', keep = 'first')
w6 = w6.sort_values(by=['device_id', 'date'])
w6 = w6.drop_duplicates('device_id', keep = 'first')
w7 = w7.sort_values(by=['device_id', 'date'])
w7 = w7.drop_duplicates('device_id', keep = 'first')

In [7]:
w1.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w2.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w3.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w4.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w5.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w6.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w7.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']

In [8]:
w1 = w1.drop(columns = ['date'])
w2 = w2.drop(columns = ['date'])
w3 = w3.drop(columns = ['date'])
w4 = w4.drop(columns = ['date'])
w5 = w5.drop(columns = ['date'])
w6 = w6.drop(columns = ['date'])
w7 = w7.drop(columns = ['date'])

# Algoritmos

In [9]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

In [10]:
X, y = w1.iloc[:,:-1], w1.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg = xgb.XGBRegressor(objective ='reg:linear', 
                colsample_bytree = 0.9, learning_rate = 0.80,
                max_depth = 5, alpha = 10, n_estimators = 10)
xg_reg.fit(X, y)
preds = xg_reg.predict(w4.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w4.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


[22:03:27] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
RMSE: 73512.728948


In [11]:
X, y = w2.iloc[:,:-1], w2.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg.fit(X, y)
preds = xg_reg.predict(w5.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w5.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


[22:03:30] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
RMSE: 74134.695818


In [12]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg.fit(X, y)
preds = xg_reg.predict(w6.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w6.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


[22:03:32] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
RMSE: 74749.107149


In [13]:
X, y = w4.iloc[:,:-1], w4.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg.fit(X, y)
preds = xg_reg.predict(w7.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w7.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


[22:03:34] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
RMSE: 114353.016952


In [14]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg.fit(X, y)

/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/xgboost/core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


[22:03:36] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.9, gamma=0,
             importance_type='gain', learning_rate=0.8, max_delta_step=0,
             max_depth=5, min_child_weight=1, missing=None, n_estimators=10,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

## Target

In [28]:
targets_st = pd.read_csv('../datos/target_competencia_ids.csv')
targets_st = targets_st[~targets_st['ref_hash'].str.contains('_sc')]
targets_st['ref_hash'] = targets_st['ref_hash'].map(lambda x: str(x)[:-3])

In [29]:
targets_st['ref_hash'] = targets_st['ref_hash'].astype(np.int64)
targets_st.columns = ['device_id', 'date_dif']

In [30]:
auctions_without_duplicates = auctions.drop_duplicates(subset = 'device_id')

In [31]:
targets_st = targets_st.merge(auctions_without_duplicates[['device_id', 'ref_type_id', 'source_id']], on = 'device_id', how = 'left')

In [32]:
targets_st = targets_st.drop(columns = ['date_dif'])

In [33]:
predictions_sc_xgb = xg_reg.predict(targets_st)

## Bagging

In [34]:
from sklearn.ensemble import BaggingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor

In [35]:
X, y = w1.iloc[:,:-1], w1.iloc[:,-1]
bagging = BaggingRegressor(KNeighborsRegressor(), max_samples=0.5, max_features=0.5)
bagging.fit(X, y)

BaggingRegressor(base_estimator=KNeighborsRegressor(algorithm='auto',
                                                    leaf_size=30,
                                                    metric='minkowski',
                                                    metric_params=None,
                                                    n_jobs=None, n_neighbors=5,
                                                    p=2, weights='uniform'),
                 bootstrap=True, bootstrap_features=False, max_features=0.5,
                 max_samples=0.5, n_estimators=10, n_jobs=None, oob_score=False,
                 random_state=None, verbose=0, warm_start=False)

In [36]:

preds = bagging.predict(w4.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w4.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 73879.585038


In [37]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
bagging = BaggingRegressor(KNeighborsRegressor(), max_samples=0.5, max_features=0.5)
bagging.fit(X, y)
predictions_sc_bagging = bagging.predict(targets_st)

# AdaBoost

In [38]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
regr = AdaBoostRegressor(random_state=0, n_estimators=50, learning_rate=0.1)
regr.fit(X, y) 
preds = regr.predict(w6.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w6.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 75208.496958


In [39]:
X, y = w6.iloc[:,:-1], w6.iloc[:,-1]
regr = AdaBoostRegressor(random_state=0, n_estimators=50, learning_rate=0.1)
regr.fit(X, y) 
predictions_sc_adaboost = regr.predict(targets_st)

## LGBM

In [41]:
import lightgbm as lgb

In [42]:
lgb_train = lgb.Dataset(w1.iloc[:,:-1], w1.iloc[:,-1])
lgb_eval = lgb.Dataset(w4.iloc[:,:-1], w4.iloc[:,-1], reference=lgb_train)
params = {
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': {'l2', 'l1'},
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}
gbm = lgb.train(params, lgb_train, num_boost_round=20, valid_sets=lgb_eval, early_stopping_rounds=10)
preds = gbm.predict(w4.iloc[:,:-1], num_iteration=gbm.best_iteration)
rmse = np.sqrt(mean_squared_error(w4.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

[1]	valid_0's l2: 5.38518e+09	valid_0's l1: 60515.1
Training until validation scores don't improve for 10 rounds.
[2]	valid_0's l2: 5.38504e+09	valid_0's l1: 60514.8
[3]	valid_0's l2: 5.38492e+09	valid_0's l1: 60514.6
[4]	valid_0's l2: 5.38446e+09	valid_0's l1: 60513.2
[5]	valid_0's l2: 5.38412e+09	valid_0's l1: 60512.3
[6]	valid_0's l2: 5.3838e+09	valid_0's l1: 60512.1
[7]	valid_0's l2: 5.38373e+09	valid_0's l1: 60512.5
[8]	valid_0's l2: 5.38362e+09	valid_0's l1: 60512.2
[9]	valid_0's l2: 5.38353e+09	valid_0's l1: 60512
[10]	valid_0's l2: 5.38344e+09	valid_0's l1: 60512.8
[11]	valid_0's l2: 5.38336e+09	valid_0's l1: 60513.2
[12]	valid_0's l2: 5.38336e+09	valid_0's l1: 60514.1
[13]	valid_0's l2: 5.38344e+09	valid_0's l1: 60515.5
[14]	valid_0's l2: 5.38359e+09	valid_0's l1: 60516.9
[15]	valid_0's l2: 5.38378e+09	valid_0's l1: 60518.9
[16]	valid_0's l2: 5.38406e+09	valid_0's l1: 60521.6
[17]	valid_0's l2: 5.38401e+09	valid_0's l1: 60522
[18]	valid_0's l2: 5.38431e+09	valid_0's l1: 60524.

In [43]:
lgb_train = lgb.Dataset(w3.iloc[:,:-1], w3.iloc[:,-1])
lgb_eval = lgb.Dataset(w6.iloc[:,:-1], w6.iloc[:,-1], reference=lgb_train)
params = {
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': {'l2', 'l1'},
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}
gbm = lgb.train(params, lgb_train, num_boost_round=20, valid_sets=lgb_eval, early_stopping_rounds=10)
preds = gbm.predict(w6.iloc[:,:-1], num_iteration=gbm.best_iteration)
rmse = np.sqrt(mean_squared_error(w6.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

[1]	valid_0's l2: 5.6107e+09	valid_0's l1: 62913.7
Training until validation scores don't improve for 10 rounds.
[2]	valid_0's l2: 5.61061e+09	valid_0's l1: 62914.6
[3]	valid_0's l2: 5.61056e+09	valid_0's l1: 62915.5
[4]	valid_0's l2: 5.60747e+09	valid_0's l1: 62894
[5]	valid_0's l2: 5.6047e+09	valid_0's l1: 62874.2
[6]	valid_0's l2: 5.60186e+09	valid_0's l1: 62852.8
[7]	valid_0's l2: 5.59971e+09	valid_0's l1: 62835.4
[8]	valid_0's l2: 5.59962e+09	valid_0's l1: 62835
[9]	valid_0's l2: 5.59956e+09	valid_0's l1: 62834.8
[10]	valid_0's l2: 5.59729e+09	valid_0's l1: 62816.5
[11]	valid_0's l2: 5.59518e+09	valid_0's l1: 62798.3
[12]	valid_0's l2: 5.59331e+09	valid_0's l1: 62782.3
[13]	valid_0's l2: 5.59166e+09	valid_0's l1: 62769.4
[14]	valid_0's l2: 5.59045e+09	valid_0's l1: 62760.3
[15]	valid_0's l2: 5.58914e+09	valid_0's l1: 62751.8
[16]	valid_0's l2: 5.58829e+09	valid_0's l1: 62746.5
[17]	valid_0's l2: 5.58824e+09	valid_0's l1: 62746.1
[18]	valid_0's l2: 5.58749e+09	valid_0's l1: 62741.4

In [44]:
predictions_sc_lgbm = gbm.predict(targets_st)

## Random Forest

In [45]:
from sklearn.ensemble import RandomForestRegressor

In [46]:
rf = RandomForestRegressor(n_estimators=10, criterion='mse', max_depth=5, min_samples_split=2, 
                           min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', 
                           max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, 
                           bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, 
                           warm_start=False)

In [47]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
rf.fit(X, y)
preds = rf.predict(w6.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w6.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 74736.066040


In [48]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
rf.fit(X, y)
predictions_sc_rf = rf.predict(targets_st)

# Promedio las predicciones y actualizo el target


In [49]:
predictions_st = np.add(np.add(np.add(np.add(predictions_sc_xgb,predictions_sc_bagging), predictions_sc_adaboost), predictions_sc_lgbm),predictions_sc_rf)
predictions_st = predictions_st / 5

In [50]:
predictions_st

array([84799.68958788, 90636.06640109, 83216.94580061, ...,
       80779.25970427, 88861.07225388, 84289.65786745])

In [51]:
predictions_sc_xgb

array([81649.58 , 90176.14 , 82955.086, ..., 74775.445, 82955.086,
       81649.58 ], dtype=float32)

In [52]:
predictions_sc_bagging

array([ 92947.29298678,  96430.9601311 ,  78029.03893708, ...,
        91090.454727  , 106249.67120344,  90397.1343846 ])

In [53]:
predictions_sc_adaboost

array([84520.71140233, 90143.37067537, 89747.2822376 , ...,
       84278.2092015 , 89747.2822376 , 84520.71140233])

In [54]:
predictions_sc_lgbm

array([82812.10275368, 87072.78872871, 83284.55921923, ...,
       79636.97994539, 83284.55921923, 82812.10275368])

In [55]:
predictions_sc_rf

array([82068.76267163, 89357.07184526, 82068.76267163, ...,
       74115.20933499, 82068.76267163, 82068.76267163])

In [56]:
for pred in predictions_st: print(pred)

84799.68958788412
90636.06640108812
83216.94580060811
90471.96325443455
81718.32184542812
89214.92467109056
86110.77910866811
86779.38558011211
83536.68145464412
85838.08630040812
85686.42403251394
82099.8845538029
96508.05784992424
84849.03017010656
83324.62283291794
105824.72182828716
78936.79788510347
87478.7538687241
86338.98334824012
84571.43763618011
79207.77482230683
95233.97326988424
87568.28381289612
90725.56582287213
89808.31486920011
91229.43975289213
88097.14217590811
90362.74810581212
88172.5914765641
84670.50774861794
86282.51577253612
88548.7111815161
87244.60444813213
93105.54391073063
89341.19616540012
89369.91544515794
88785.43966421056
84217.0997088721
90933.37163088011
82677.6023975338
88342.85629733212
90643.68185136412
84797.12338279611
87991.43820007611
84687.59030877227
102662.47561692559
86263.69258911807
83412.76608242812
90595.17435570656
81031.81957773611
93030.10959159237
82566.6778235161
80331.5968424658
86331.60390756655
84670.1536756667
83128.34186384811

79884.48781185315
86153.47502556116
85255.89170527716
93142.55214434686
100012.43879532322
87146.35582612516
77593.23626289325
79803.24532641316
82676.11554957715
84594.81682468115
92112.7362651485
77426.63189371323
89977.00745134916
86198.2444479221
95313.3329003005
84930.4580535021
75840.61930156124
89340.1900191725
93744.07900578051
86425.43681821716
88879.39204906812
87025.71944434116
102256.40720326988
82708.94780948515
94739.04872434038
85313.77339272165
90989.72236408116
84054.04826954637
82200.88270243611
88929.91116861638
79932.56598068717
89221.00796700516
88654.2807419301
94885.00553230825
85962.45997913316
105445.03642319523
93915.68164438449
89402.07296249316
89108.15556489573
88668.81393086052
105367.28993134321
85179.43958362566
85599.12650629715
84253.04836948516
86552.5545438701
102779.95137975922
83780.13721280915
85973.66461983314
88209.71496050115
83832.28244907715
89442.2890467181
84027.76232957316
85485.43364639315
88660.88355308838
82666.69610091366
93520.2408187

90062.9480092604
79549.17505219692
81332.69972616891
92794.35212555976
83987.1462306391
90277.07951404135
85599.73911712441
84905.87179183241
83280.98195183641
86217.08702101241
86356.0467001724
84976.34706311241
88832.01648013736
85976.0488657284
104976.27094978074
87956.0239925804
91699.47503786841
87298.8399254524
86350.84214068812
90651.8531902364
88207.10588764811
80132.43050886311
84829.42442242042
84164.29968199962
90658.86247496249
102742.59228290939
80399.39274336092
85180.7249424711
86166.00685301241
84935.7603354641
90412.22948329165
84097.22446860842
84158.36991882042
86468.6416190164
91399.35688703976
84683.55961805202
92975.73723168776
86378.8821187284
89640.87783780841
87316.1280209364
85269.25160182011
89164.44044388775
85352.65369340136
86439.50564402042
92530.3084391841
87932.59154759641
85176.95431798042
82846.41988852041
87385.04933420537
90417.73733684536
87747.61346739737
82437.6684459004
84319.14018662936
89060.11224450442
83941.25835502248
81415.57278484649
8833

# Guardo los modelos de predicción

In [60]:
from joblib import dump 
  
# Guardo bagging como un pickle file 
dump(xg_reg, 'xg_reg.pkl') 
dump(bagging, 'bagging.pkl') 
dump(regr, 'regr.pkl') 
dump(gbm, 'gbm.pkl') 
dump(rf, 'rf.pkl') 


['rf.pkl']

# Pruebo que los modelos que almacené funcionan igual que los anteriores

## xg_reg

In [62]:
# Cargo el modelo del archivo
xg_reg_from_joblib = joblib.load('xg_reg.pkl')  
  
# Lo uso para predecir
predictions_sc_xgb_from_joblib = xg_reg_from_joblib.predict(targets_st)

predictions_sc_xgb_from_joblib

[00:14:58] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


array([81649.58 , 90176.14 , 82955.086, ..., 74775.445, 82955.086,
       81649.58 ], dtype=float32)