In [1]:
import pandas as pd
import numpy as np

In [2]:
auctions = pd.read_csv('auctions.csv.gzip', compression = 'gzip', low_memory=False)

In [3]:
auctions['date'] = pd.to_datetime(auctions['date'])

In [4]:
w1 = auctions[auctions['date'].dt.day < 21]
w2 = auctions[(auctions['date'].dt.day > 18) & (auctions['date'].dt.day < 22)]
w3 = auctions[(auctions['date'].dt.day > 19) & (auctions['date'].dt.day < 23)]
w4 = auctions[(auctions['date'].dt.day > 20) & (auctions['date'].dt.day < 24)]
w5 = auctions[(auctions['date'].dt.day > 21) & (auctions['date'].dt.day < 25)]
w6 = auctions[(auctions['date'].dt.day > 22) & (auctions['date'].dt.day < 26)]
w7 = auctions[(auctions['date'].dt.day > 23) & (auctions['date'].dt.day < 27)]

In [5]:
windowStart = pd.to_datetime("2019-04-18 00:00:00.000000")
w1['timeFromWindowStart'] = (w1['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-19 00:00:00.000000")
w2['timeFromWindowStart'] = (w2['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-20 00:00:00.000000")
w3['timeFromWindowStart'] = (w3['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-21 00:00:00.000000")
w4['timeFromWindowStart'] = (w4['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-22 00:00:00.000000")
w5['timeFromWindowStart'] = (w5['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-23 00:00:00.000000")
w6['timeFromWindowStart'] = (w6['date'] - windowStart)/np.timedelta64(1,'s')
windowStart = pd.to_datetime("2019-04-23 00:00:00.000000")
w7['timeFromWindowStart'] = (w7['date'] - windowStart)/np.timedelta64(1,'s')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org

In [6]:
w1 = w1.sort_values(by=['device_id', 'date'])
w1 = w1.drop_duplicates('device_id', keep = 'first')
w2 = w2.sort_values(by=['device_id', 'date'])
w2 = w2.drop_duplicates('device_id', keep = 'first')
w3 = w3.sort_values(by=['device_id', 'date'])
w3 = w3.drop_duplicates('device_id', keep = 'first')
w4 = w4.sort_values(by=['device_id', 'date'])
w4 = w4.drop_duplicates('device_id', keep = 'first')
w5 = w5.sort_values(by=['device_id', 'date'])
w5 = w5.drop_duplicates('device_id', keep = 'first')
w6 = w6.sort_values(by=['device_id', 'date'])
w6 = w6.drop_duplicates('device_id', keep = 'first')
w7 = w7.sort_values(by=['device_id', 'date'])
w7 = w7.drop_duplicates('device_id', keep = 'first')

In [7]:
w1.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w2.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w3.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w4.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w5.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w6.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']
w7.columns = ['date', 'device_id', 'ref_type_id', 'source_id', 'st']

In [8]:
w1 = w1.drop(columns = ['date'])
w2 = w2.drop(columns = ['date'])
w3 = w3.drop(columns = ['date'])
w4 = w4.drop(columns = ['date'])
w5 = w5.drop(columns = ['date'])
w6 = w6.drop(columns = ['date'])
w7 = w7.drop(columns = ['date'])

# Algoritmos

In [9]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

In [12]:
X, y = w1.iloc[:,:-1], w1.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg = xgb.XGBRegressor(objective ='reg:linear', 
                colsample_bytree = 0.9, learning_rate = 0.80,
                max_depth = 5, alpha = 10, n_estimators = 10)
xg_reg.fit(X, y)
preds = xg_reg.predict(w4.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w4.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 73515.714903


In [13]:
X, y = w2.iloc[:,:-1], w2.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg.fit(X, y)
preds = xg_reg.predict(w5.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w5.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 74121.174798


In [14]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg.fit(X, y)
preds = xg_reg.predict(w6.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w6.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 74751.537618


In [16]:
X, y = w4.iloc[:,:-1], w4.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg.fit(X, y)
preds = xg_reg.predict(w7.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w7.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 114340.456509


In [87]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
data_dmatrix = xgb.DMatrix(data=X,label=y)
xg_reg.fit(X, y)

XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.9, gamma=0, learning_rate=0.8, max_delta_step=0,
       max_depth=5, min_child_weight=1, missing=None, n_estimators=10,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

## Target

In [18]:
targets_st = pd.read_csv('target_competencia_ids.csv')
targets_st = targets_st[~targets_st['ref_hash'].str.contains('_sc')]
targets_st['ref_hash'] = targets_st['ref_hash'].map(lambda x: str(x)[:-3])

In [19]:
targets_st['ref_hash'] = targets_st['ref_hash'].astype(np.int64)
targets_st.columns = ['device_id', 'date_dif']

In [20]:
auctions_without_duplicates = auctions.drop_duplicates(subset = 'device_id')

In [21]:
targets_st = targets_st.merge(auctions_without_duplicates[['device_id', 'ref_type_id', 'source_id']], on = 'device_id', how = 'left')

In [22]:
targets_st = targets_st.drop(columns = ['date_dif'])

In [88]:
predictions_sc_xgb = xg_reg.predict(targets_st)

## Bagging

In [25]:
from sklearn.ensemble import BaggingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor

In [26]:
X, y = w1.iloc[:,:-1], w1.iloc[:,-1]
bagging = BaggingRegressor(KNeighborsRegressor(), max_samples=0.5, max_features=0.5)
bagging.fit(X, y)
preds = bagging.predict(w4.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w4.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 74368.994104


In [89]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
bagging = BaggingRegressor(KNeighborsRegressor(), max_samples=0.5, max_features=0.5)
bagging.fit(X, y)
predictions_sc_bagging = bagging.predict(targets_st)

# AdaBoost

In [106]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
regr = AdaBoostRegressor(random_state=0, n_estimators=50, learning_rate=0.1)
regr.fit(X, y) 
preds = regr.predict(w6.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w6.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 75208.496958


In [107]:
X, y = w6.iloc[:,:-1], w6.iloc[:,-1]
regr = AdaBoostRegressor(random_state=0, n_estimators=50, learning_rate=0.1)
regr.fit(X, y) 
predictions_sc_adaboost = regr.predict(targets_st)

## LGBM

In [31]:
import lightgbm as lgb

In [36]:
lgb_train = lgb.Dataset(w1.iloc[:,:-1], w1.iloc[:,-1])
lgb_eval = lgb.Dataset(w4.iloc[:,:-1], w4.iloc[:,-1], reference=lgb_train)
params = {
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': {'l2', 'l1'},
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}
gbm = lgb.train(params, lgb_train, num_boost_round=20, valid_sets=lgb_eval, early_stopping_rounds=10)
preds = gbm.predict(w4.iloc[:,:-1], num_iteration=gbm.best_iteration)
rmse = np.sqrt(mean_squared_error(w4.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

[1]	valid_0's l1: 60515.1	valid_0's l2: 5.38516e+09
Training until validation scores don't improve for 10 rounds.
[2]	valid_0's l1: 60514.8	valid_0's l2: 5.38501e+09
[3]	valid_0's l1: 60514.7	valid_0's l2: 5.38487e+09
[4]	valid_0's l1: 60513.2	valid_0's l2: 5.38438e+09
[5]	valid_0's l1: 60512.3	valid_0's l2: 5.38405e+09
[6]	valid_0's l1: 60512.8	valid_0's l2: 5.38366e+09
[7]	valid_0's l1: 60514.1	valid_0's l2: 5.38354e+09
[8]	valid_0's l1: 60514.4	valid_0's l2: 5.38343e+09
[9]	valid_0's l1: 60514.6	valid_0's l2: 5.38333e+09
[10]	valid_0's l1: 60516.1	valid_0's l2: 5.38319e+09
[11]	valid_0's l1: 60517.4	valid_0's l2: 5.38319e+09
[12]	valid_0's l1: 60519.1	valid_0's l2: 5.38327e+09
[13]	valid_0's l1: 60521.2	valid_0's l2: 5.38343e+09
[14]	valid_0's l1: 60523.2	valid_0's l2: 5.38363e+09
[15]	valid_0's l1: 60525.8	valid_0's l2: 5.38389e+09
Early stopping, best iteration is:
[5]	valid_0's l1: 60512.3	valid_0's l2: 5.38405e+09
RMSE: 73376.058304


In [45]:
lgb_train = lgb.Dataset(w3.iloc[:,:-1], w3.iloc[:,-1])
lgb_eval = lgb.Dataset(w6.iloc[:,:-1], w6.iloc[:,-1], reference=lgb_train)
params = {
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': {'l2', 'l1'},
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}
gbm = lgb.train(params, lgb_train, num_boost_round=20, valid_sets=lgb_eval, early_stopping_rounds=10)
preds = gbm.predict(w6.iloc[:,:-1], num_iteration=gbm.best_iteration)
rmse = np.sqrt(mean_squared_error(w6.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

[1]	valid_0's l1: 62913.8	valid_0's l2: 5.61075e+09
Training until validation scores don't improve for 10 rounds.
[2]	valid_0's l1: 62914.4	valid_0's l2: 5.61062e+09
[3]	valid_0's l1: 62915	valid_0's l2: 5.61054e+09
[4]	valid_0's l1: 62893.7	valid_0's l2: 5.60749e+09
[5]	valid_0's l1: 62874.2	valid_0's l2: 5.6048e+09
[6]	valid_0's l1: 62853.2	valid_0's l2: 5.60203e+09
[7]	valid_0's l1: 62835.8	valid_0's l2: 5.59991e+09
[8]	valid_0's l1: 62835.7	valid_0's l2: 5.59983e+09
[9]	valid_0's l1: 62835.7	valid_0's l2: 5.59976e+09
[10]	valid_0's l1: 62817.9	valid_0's l2: 5.59757e+09
[11]	valid_0's l1: 62801.4	valid_0's l2: 5.59554e+09
[12]	valid_0's l1: 62787.1	valid_0's l2: 5.59374e+09
[13]	valid_0's l1: 62775.6	valid_0's l2: 5.59214e+09
[14]	valid_0's l1: 62767.5	valid_0's l2: 5.59098e+09
[15]	valid_0's l1: 62759.9	valid_0's l2: 5.5897e+09
[16]	valid_0's l1: 62755.1	valid_0's l2: 5.58876e+09
[17]	valid_0's l1: 62755.7	valid_0's l2: 5.58876e+09
[18]	valid_0's l1: 62751.6	valid_0's l2: 5.58794e+

In [46]:
predictions_sc_lgbm = gbm.predict(targets_st)

## Random Forest

In [61]:
from sklearn.ensemble import RandomForestRegressor

In [62]:
rf = RandomForestRegressor(n_estimators=10, criterion='mse', max_depth=5, min_samples_split=2, 
                           min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', 
                           max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, 
                           bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, 
                           warm_start=False)

In [84]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
rf.fit(X, y)
preds = rf.predict(w6.iloc[:,:-1])
rmse = np.sqrt(mean_squared_error(w6.iloc[:,-1], preds))
print("RMSE: %f" % (rmse))

RMSE: 74734.471768


In [85]:
X, y = w3.iloc[:,:-1], w3.iloc[:,-1]
rf.fit(X, y)
predictions_sc_rf = rf.predict(targets_st)

# Promedio las predicciones y actualizo el target


In [111]:
predictions_st = np.add(np.add(np.add(np.add(predictions_sc_xgb,predictions_sc_bagging), predictions_sc_adaboost), predictions_sc_lgbm),predictions_sc_rf)
predictions_st = predictions_st / 5

In [112]:
predictions_st

array([80650.87320339, 88593.6838886 , 82617.62827496, ...,
       79225.81242383, 82617.62827496, 80650.87320339])

In [113]:
predictions_sc_xgb

array([81136.2  , 89816.734, 82417.99 , ..., 74079.54 , 82417.99 ,
       81136.2  ], dtype=float32)

In [114]:
predictions_sc_bagging

array([72840.10466558, 86160.14478608, 75639.1132727 , ...,
       84415.53025916, 75639.1132727 , 72840.10466558])

In [115]:
predictions_sc_adaboost

array([84520.71140233, 90143.37067537, 89747.2822376 , ...,
       84278.2092015 , 89747.2822376 , 84520.71140233])

In [116]:
predictions_sc_lgbm

array([82781.1343077 , 87278.20072997, 83307.54116063, ...,
       79213.19936629, 83307.54116063, 82781.1343077 ])

In [117]:
predictions_sc_rf

array([81976.21251635, 89569.96887658, 81976.21251635, ...,
       74142.5842297 , 81976.21251635, 81976.21251635])

In [118]:
for pred in predictions_st: print(pred)

80650.87320339218
88593.68388859842
82617.62827495634
83250.8093593307
80650.87320339218
83250.8093593307
82617.62827495634
80650.87320339218
80650.87320339218
80650.87320339218
81770.03841887144
79773.0165455756
90492.39514306029
83250.8093593307
81770.03841887144
104679.55853957449
79592.80512720619
82617.62827495634
80650.87320339218
82617.62827495634
79715.75529206176
90492.39514306029
80650.87320339218
80650.87320339218
84009.69181495432
80650.87320339218
80750.67460037772
82617.62827495634
80650.87320339218
81770.03841887144
80650.87320339218
80650.87320339218
80750.67460037772
92664.04690630463
82617.62827495634
81770.03841887144
83250.8093593307
80650.87320339218
82617.62827495634
79448.30114207049
82617.62827495634
80650.87320339218
80650.87320339218
80650.87320339218
85682.78242930215
101430.37973087202
81581.39849211925
80650.87320339218
83250.8093593307
80650.87320339218
90140.81500028043
82617.62827495634
79448.30114207049
83250.8093593307
82908.89609449789
80650.873203392